### ISSUE TITLE
Missing packages to pip install PyOpenSSL

### ISSUE THREAD

**Issue by jaevans** [geerlingguy/raspberry-pi-dramble#116]
Thanks for the great project, I've been working a few weeks attempting to get a working k8s cluster on my Pis, and I've had the most success with this project!

I did however run into a couple of missing dev packages on the latest stretch-lite image. Specifically, `libffi-dev` and `libssl-dev` were missing. 

Opening issue, PR will follow.

**Comment by geerlingguy** [comment]
Fixed via above PR. Confirmed that entire playbook runs on a fresh set of Pis!
