### ISSUE TITLE
Where is the playboooks located?

### ISSUE THREAD

**Issue by poon64** [geerlingguy/raspberry-pi-dramble#136]
In the documentation it's referring to the playbooks directory, but it can't be found in the repository. 
Like this, 
 ansible-galaxy install -r playbooks/requirements.yml --force
ansible-playbook -i inventory playbooks/drupal/main.yml

**Comment by geerlingguy** [comment]
@poon64 - If you're using the latest version of the Dramble cluster (which uses Kubernetes), there is no more `playbooks` directory; as mentioned in the README (https://github.com/geerlingguy/raspberry-pi-dramble#setting-up-the-pis), a couple of the pages on the Wiki still need to be updated, as I'm working quite a bit on making sure the Kubernetes setup process is working well before I complete the documentation edits.

**Comment by geerlingguy** [comment]
See related: #133
