### ISSUE TITLE
Build scripts (and/or just a user guide) for demo of Ansible + Blinksticks

### ISSUE THREAD

**Issue by geerlingguy** [geerlingguy/raspberry-pi-dramble#143]
From #112, I've broken out this issue:

* [x] Build a few scripts that allow easy remote control of LEDs (for use with demoing Ansible ad-hoc/playbook orchestration).

Basically, I want to be able to do some slick things in a demo like:

1. Stop the `dramble-node-monitor` service so the LEDs go off and the Pis are not monitoring node status anymore.
1. Turn the blinkstick blue, using serial=1
1. Turn the blinkstick green, using serial=2
1. Turn the blinkstick off, with no serial (so all at once)

It would also be sorta cool if I built a sidecar pod to the Drupal pod that would flash the blinkstick any time a request was made to that container (e.g. watch the Apache log?)... but that would probably be something to break out into a separate feature.

I would also like to document the setup and use of blinksticks (vs soldered LED boards) in the Dramble Wiki.

**Comment by geerlingguy** [comment]
See: https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/testing/presentation/SCRIPT.md

**Comment by SamTheFishy** [comment]
Thanks very useful.
