### ISSUE TITLE
Setup networking assigns wrong gateway.

### ISSUE THREAD

**Issue by NiftyMist** [geerlingguy/raspberry-pi-dramble#179]
I ran into an issue when running the networking setup that would cause me to be unable to ssh to my pis after reboots.  I'm not sure if this is known or not but thought I would open an issue.  I discovered that is was due to the pis having the wrong gateway.  My pis are in a different subnet from my ansible control node.  I have forked the repo and added a new var for set networking where a user can insert the correct value in the `vars.yml`, then the correct gateway is added in with the template.  Would it be possible to have my contribution merged?

**Comment by geerlingguy** [comment]
Yes; that should probably be a variable anyways; just make it a variable with the default set correctly and that would be simple enough to merge.
