### ISSUE TITLE
What is Idle for the benchmarks?

### ISSUE THREAD

**Issue by ShishirPatil** [geerlingguy/raspberry-pi-dramble#180]
Hi,

What exactly is the characterization of ''idle'' in the [Power Consumption Benchmarks](https://www.pidramble.com/wiki/benchmarks/power-consumption)? Does it mean the RPi is in a while one loop, or does it mean sleep, etc?

Further, for the ''400% CPU load (stress --cpu 4)'' is the WiFi module on, and is it connected to WiFi?

Thanks, and apologies if it has been answered elsewhere.

**Comment by geerlingguy** [comment]
For idle, that means I boot the Pi with a fresh new copy of the OS, then wait 5 minutes, and make sure no other extra processes or software is running. (System load around 0.00 or 0.01).

For CPU stress, WiFi is on but is not connected.

Thanks!
