### ISSUE TITLE
Wiki for "Raspberry Pi 'Dog Bone' Stackable Case" has broken link

### ISSUE THREAD

**Issue by mglaman** [geerlingguy/raspberry-pi-dramble#181]
There are two links: the eBay link is dead, and "case" links to an active Amazon listing

```
<td>
  <a href="https://www.ebay.com/itm/271648357906">Raspberry Pi 'Dog Bone' Stackable</a>
  <a href="https://www.amazon.com/Yahboom-Raspberry-Cluster-6-Layers-Enclosure/.......">&nbsp;Case</a>
</td>
````

**Comment by geerlingguy** [comment]
Though it's not super clear, the code/content for the site is over in https://github.com/geerlingguy/drupal-for-kubernetes/issues/36 — so closing this issue and moving to there. Thanks for spotting this and filing the issue!
