### ISSUE TITLE
overclock the microSD card reader on a Raspberry Pi model 3 B+ 

### ISSUE THREAD

**Issue by voipas** [geerlingguy/raspberry-pi-dramble#186]
Hey,
  I wanted to ask you, if you tried to overclock the microSD card reader on a Raspberry Pi 3 ?
I'm using debian OS and changed config.txt based on your blog posts, but after reboot it is not affecting... 
I wonder, if you tried to do on this Raspberry Pi model 3 B+ model?

Thanks

**Comment by geerlingguy** [comment]
I believe I only tried to do it on the 3 B+ and 4 B, and in both cases that worked.
