### ISSUE TITLE
flannel manifest patching

### ISSUE THREAD

**Issue by kentahikaru** [geerlingguy/raspberry-pi-dramble#191]
Hello, i don't see patching of flannel manifest in this project similar to:
https://github.com/geerlingguy/ansible-for-kubernetes/blob/master/cluster-local-vms/tasks/vagrant-setup.yml

How is it possible ?
Is it somehow hidden or not necessary?
Thanks.

**Comment by geerlingguy** [comment]
That's a good question. I haven't touched the Vagrant configuration inside _this_ project for a year or so, so I'm not even 100% sure it's still working. It might be, I just haven't tried it (focused on the Pis themselves for now...).

If you run the project in Vagrant and see an error, please open up a new issue to follow-up on that.
