### ISSUE TITLE
Blink Sticks

### ISSUE THREAD

**Issue by garylefebvreg** [geerlingguy/raspberry-pi-dramble#196]
Is there software i need to install to get the blink sticks to work?

**Comment by geerlingguy** [comment]
The [Blinkstick Role](https://github.com/geerlingguy/raspberry-pi-dramble/tree/master/roles/leds-blinkstick) sets up the necessary software to set them red/green depending on kubelet status.

You would need to toggle the blinkstick setting to `true` to get that role to apply, though; see https://github.com/geerlingguy/raspberry-pi-dramble/blob/master/example.config.yml#L27-L29

**Comment by garylefebvreg** [comment]
BlinkStick seems not to be working...

# LED Configuration.
led_enable_gpio: false
led_enable_blinkstick: true
