### ISSUE TITLE
microsd-benchmark iozone compile error

### ISSUE THREAD

**Issue by jaui** [geerlingguy/raspberry-pi-dramble#221]
running 
`$ sudo ./microsd-benchmarks.sh`
under the latest Raspberry Pi OS based on bullseye (debian 11)
raises an error during compilation of **iozone**
```
/usr/bin/ld: libbif.o:(.bss+0x0): multiple definition of `junk'; iozone_linux-arm.o:(.bss+0x0): first defined here
collect2: error: ld returned 1 exit status
make: *** [makefile:221: linux-arm] Error 1
```

The hint from wesite
https://github.com/phoronix-test-suite/test-profiles/issues/139
add a `CFLAGS=-fcommon` statement to make helped.

`$ make CFLAGS=-fcommon linux-arm `
runs  smootly.

Would you please add this fix to make of iozone.

**Comment by geerlingguy** [comment]
@jaui - I've just been testing this on two different builds of Raspberry Pi OS Bullseye over the past week, and haven't had any trouble building—though that was on the `disk-benchmarks.sh` script. Maybe the iozone version is old and needs updating?

**Comment by 2sls** [comment]
I had same issue  - for me, updating the version from 489 to 492 in the microsd-benchmark.sh file fixed everything

**Comment by geerlingguy** [comment]
Bumped the version in all three files to 492 :)
