### ISSUE TITLE
Network bridging not properly enabled

### ISSUE THREAD

**Issue by Elfinhope** [geerlingguy/raspberry-pi-dramble#223]
On running of the playbook, I got two errors related to network forwarding.  First, /proc/sys/net/ipv4/ip_forward was not set to 1 and second /proc/sys/net/bridge/bridge-nf-call-iptables did not exist.  Both were easily solved the first by uncommenting the appropriate line in sysctl.conf and the second by running modprobe to load br_ipforward (I also added net.bridge.bridge-nf-call-iptables=1 to my sysctl.conf file as well).
I have Raspbian 64-bit lite (I believe Bullseye) on Pi 4s.  I've used this playbook previously and did not have this problem, so there must have been some change when Bullseye came out.

**Comment by Elfinhope** [comment]
Note, the modprobe above should have been br_netfilter not br_ipforward.  In addition, I had to add br_netfilter to my /etc/modules file.

**Comment by sdaynjax** [comment]
I think I'm having the same issue, but can you provide more details on your fix.  Also, running modprobe to load br_ipforward  was this on all the pi's?  Can you give me the exact command?  I'm running 3 PI 3 B+ and my master is PI 4. I know Ansible but all this other is way over my head. Any help would be really appreciated.
