### ISSUE TITLE
error while setup

### ISSUE THREAD

**Issue by saikatbepari** [geerlingguy/raspberry-pi-dramble#228]
TASK [geerlingguy.kubernetes : Ensure dependencies are installed.] **********************************************
ok: [kube2]
ok: [kube1]

TASK [geerlingguy.kubernetes : Add Kubernetes apt key.] *********************************************************
fatal: [kube2]: FAILED! => changed=false
  msg: 'Failed to connect to packages.cloud.google.com at port 443: [Errno -3] Temporary failure in name resolution'
  status: -1
  url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
fatal: [kube1]: FAILED! => changed=false
  msg: 'Failed to connect to packages.cloud.google.com at port 443: [Errno -3] Temporary failure in name resolution'
  status: -1
  url: https://packages.cloud.google.com/apt/doc/apt-key.gpg

PLAY RECAP ******************************************************************************************************
kube1                      : ok=37   changed=0    unreachable=0    failed=1    skipped=29   rescued=0    ignored=0
kube2                      : ok=37   changed=0    unreachable=0    failed=1    skipped=29   rescued=0    ignored=0
kube4                      : ok=0    changed=0    unreachable=0    failed=1    skipped=0    rescued=0    ignored=0

**Comment by djvdorp** [comment]
@saikatbepari does kube1/kube2 DNS resolution work?
