### ISSUE TITLE
Reccomended Poweradd for Pi Cluster

### ISSUE THREAD

**Issue by jminker** [geerlingguy/raspberry-pi-dramble#83]
Jeff,

After helping me yesterday as you did it has prompted me to follow along and attempt the Pi Cluster.  My question as I look at the output on the recommended power source if that it appears the output is 2x2.4A   2x2.1A and 2x1A   is this correct?  https://www.amazon.com/Poweradd-Family-Sized-Multi-Port-Desktop-Smartphones/dp/B00KHP6UVQ/ref=as_li_ss_tl?ie=UTF8&redirect=true&ref_=as_li_tl&linkCode=ll1&tag=mmjjg-20&linkId=e80708b1638089b2e6e582eb73a729cf

Also is this the best way to communicate with you (posting issues) or should I send them via email address.

Thanks,
John
john.minker@gmail.com

**Comment by geerlingguy** [comment]
> My question as I look at the output on the recommended power source if that it appears the output is 2x2.4A 2x2.1A and 2x1A is this correct?

Yes, that's correct... there are a few adapters that say they can deliver 2.4A across all five or six ports, but in my testing, most can only deliver a maximum amperage, so you will hit limits overall before it hits 2.4A per port.

But individual units can also vary. Best to do some testing under load and make sure whatever supply you choose has the juice to power the cluster without major issues!

> Also is this the best way to communicate with you (posting issues) or should I send them via email address.

This is definitely the best way—emails sometimes get lost, GitHub issues are forever (and easily searchable if you or I forget something five years down the road :).
