### ISSUE TITLE
dd filename mismatch on -of of dd in microsd-benchmarks.sh

### ISSUE THREAD

**Issue by gddeen** [geerlingguy/raspberry-pi-dramble#85]
dd if=/dev/zero of=${USER_HOME_PATH}test bs=8k count=50k conv=fsync; rm -f ${USER_HOME_PATH}/test

it should probably be

dd if=/dev/zero of=${USER_HOME_PATH}/test bs=8k count=50k conv=fsync; rm -f ${USER_HOME_PATH}/test

**Comment by geerlingguy** [comment]
Thanks, I fixed it in the commit linked above!
