### ISSUE TITLE
"Ensure php executable is symlinked into a standard path" not skipped

### ISSUE THREAD

**Issue by aaronkjones** [geerlingguy/raspberry-pi-dramble#89]
Should this task not be skipped if build from source is false?

> TASK [geerlingguy.php : Check if PHP is installed.] ****************************
> ok: [192.168.1.51]
> ok: [192.168.1.52]
> 
> TASK [geerlingguy.php : Clone the PHP repository.] *****************************
> skipping: [192.168.1.51]
> skipping: [192.168.1.52]
> 
> TASK [geerlingguy.php : Ensure PHP installation path exists.] ******************
> skipping: [192.168.1.51]
> skipping: [192.168.1.52]
> 
> TASK [geerlingguy.php : Build configure script.] *******************************
> skipping: [192.168.1.51]
> skipping: [192.168.1.52]
> 
> TASK [geerlingguy.php : Run configure script.] *********************************
> skipping: [192.168.1.51]
> skipping: [192.168.1.52]
> 
> TASK [geerlingguy.php : Make and install PHP.] *********************************
> skipping: [192.168.1.51] => (item=make --jobs=4) 
> skipping: [192.168.1.51] => (item=make install) 
> skipping: [192.168.1.52] => (item=make --jobs=4) 
> skipping: [192.168.1.52] => (item=make install) 
> 
> TASK [geerlingguy.php : Ensure php executable is symlinked into a standard path.] ***
> fatal: [192.168.1.51]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0777", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /opt/php/bin/php", "owner": "root", "path": "/usr/bin/php", "size": 21, "src": "/opt/php/bin/php", "state": "link", "uid": 0}
> fatal: [192.168.1.52]: FAILED! => {"changed": false, "failed": true, "gid": 0, "group": "root", "mode": "0777", "msg": "src file does not exist, use \"force=yes\" if you really want to create the link: /opt/php/bin/php", "owner": "root", "path": "/usr/bin/php", "size": 21, "src": "/opt/php/bin/php", "state": "link", "uid": 0}

Since /opt/php does not exist (php was installed with package manager, not source) it fails at this step.

**Comment by geerlingguy** [comment]
This should be working correctly at this point; I think there may have been a bug in the version of the PHP role you were using—or possibly with the Ansible version you had?

I'm closing this now, but please let me know if it's still an issue and I'll reopen.
